// src/data/products.js
export const PRODUCTS = [
  {
    id: 1,
    handle: "medicube-zero-pore-pad",
    name: "Zero Pore Pad 2.0",
    brand: "Medicube",
    tagline: "Pore-Refining Toner Pads",
    price: 29.00,
    compareAt: null,
    category: "Skincare",
    tags: ["K-Beauty", "Toner", "Pores"],
    isTrending: true,
    trendLabel: "#1 Beauty Bestseller Q1 2026",
    rating: 4.6,
    reviewCount: 18400,
    description: "Dual-action toner pads that refine pores and smooth skin texture with every swipe. AHA/BHA + Centella Asiatica for daily exfoliation that actually works.",
    ingredients: ["AHA (Glycolic Acid)", "BHA (Salicylic Acid)", "Centella Asiatica", "Niacinamide"],
    results: ["+92% pore reduction", "+88% smoother texture", "+85% radiance"],
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    color: "#E8F4F8",
    variants: ["70 Pads — $29", "140 Pads — $49"],
  },
  {
    id: 2,
    handle: "biodance-bio-collagen-mask",
    name: "Bio-Collagen Deep Mask",
    brand: "Biodance",
    tagline: "Overnight Collagen Treatment",
    price: 24.00,
    compareAt: null,
    category: "Skincare",
    tags: ["Collagen", "Overnight", "K-Beauty"],
    isTrending: true,
    trendLabel: "TikTok Viral",
    rating: 4.6,
    reviewCount: 31200,
    description: "The transparent gel mask that bonds to your skin for 8 hours. 31,000+ five-star reviews. Wake up to the most hydrated skin of your life.",
    ingredients: ["Hydrolyzed Collagen", "Niacinamide", "Glycerin", "Hyaluronic Acid"],
    results: ["+95% hydration", "+80% firmness", "+78% glow"],
    image: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&q=80",
    color: "#F0EDE8",
    variants: ["4 Masks — $24", "8 Masks — $42"],
  },
  {
    id: 3,
    handle: "tanologist-self-tan-drops",
    name: "Self-Tan Drops",
    brand: "Tanologist",
    tagline: "Customisable Bronze Serum",
    price: 16.99,
    compareAt: null,
    category: "Self Tanner",
    tags: ["Tanning", "Vegan", "Clean"],
    isTrending: true,
    trendLabel: "↑ Trending Self-Tan",
    rating: 4.4,
    reviewCount: 12800,
    description: "Mix 2–6 drops with your moisturiser for a fully customisable, streak-free tan. Vegan, fragrance-free, and dermatologist-approved.",
    ingredients: ["DHA", "Aloe Vera", "Vitamin E", "Green Tea Extract"],
    results: ["Natural bronze finish", "No streaks", "Fades evenly"],
    image: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80",
    color: "#F5EDE0",
    variants: ["Light/Medium — $16.99", "Medium/Dark — $16.99", "Dark — $16.99"],
  },
  {
    id: 4,
    handle: "rapidlash-eyelash-serum",
    name: "Eyelash & Eyebrow Serum",
    brand: "RapidLash",
    tagline: "Clinically Proven Lash Growth",
    price: 39.99,
    compareAt: 49.99,
    category: "Eye Care",
    tags: ["Lashes", "Brows", "Clinical"],
    isTrending: true,
    trendLabel: "+35% Sales Growth",
    rating: 4.3,
    reviewCount: 22500,
    description: "Clinically tested formula that visibly enhances lash length, volume, and density in 4–6 weeks. The #fullfacenomascara era starts here.",
    ingredients: ["Peptide Complex", "Biotin", "Panthenol", "Keratin"],
    results: ["+96% longer lashes", "+91% fuller brows", "+88% less breakage"],
    image: "https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    color: "#EAE8F0",
    variants: ["3ml — $39.99"],
  },
  {
    id: 5,
    handle: "ordinary-glycolic-toner",
    name: "Glycolic Acid 7% Toner",
    brand: "The Ordinary",
    tagline: "Weekly Exfoliating Treatment",
    price: 12.00,
    compareAt: null,
    category: "Skincare",
    tags: ["Exfoliant", "Glow", "Bestseller"],
    isTrending: false,
    trendLabel: null,
    rating: 4.5,
    reviewCount: 89000,
    description: "89,000 reviews don't lie. 7% glycolic acid that resurfases, brightens, and clears — at a price that makes luxury skincare feel ridiculous.",
    ingredients: ["Glycolic Acid 7%", "Ginseng Root Extract", "Tasmannia Lanceolata", "Aminomethyl Propanol"],
    results: ["+85% brighter skin", "+80% smoother texture", "+75% even tone"],
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80",
    color: "#EDF2E8",
    variants: ["240ml — $12.00"],
  },
  {
    id: 6,
    handle: "lanmeri-copper-peptide-serum",
    name: "Copper Peptide Serum 1%",
    brand: "Lanmeri",
    tagline: "Next-Gen Anti-Aging Formula",
    price: 22.00,
    compareAt: 29.00,
    category: "Skincare",
    tags: ["Peptides", "Anti-Aging", "Barrier"],
    isTrending: true,
    trendLabel: "+24% Search Growth",
    rating: 4.2,
    reviewCount: 3100,
    description: "1% GHK-Cu copper peptide — gentler than retinoids with comparable long-term results for collagen stimulation and barrier repair.",
    ingredients: ["GHK-Cu (Copper Peptide) 1%", "Hyaluronic Acid", "Niacinamide", "Vitamin C"],
    results: ["+82% collagen boost", "+79% barrier strength", "+71% firmer skin"],
    image: "https://images.unsplash.com/photo-1615397587950-3cbb55f95b91?w=600&q=80",
    hoverImage: "https://images.unsplash.com/photo-1556229010-aa3f7ff66b24?w=600&q=80",
    color: "#F0EAE8",
    variants: ["30ml — $22.00"],
  },
];

export const REVIEWS = [
  { name: "Sarah M.", location: "New York, USA", avatar: "SM", text: "The Pore Pad changed my skin in literally two weeks. My pores look smaller, my texture is smoother. I've repurchased 4 times.", product: "Zero Pore Pad 2.0", rating: 5 },
  { name: "Jessica R.", location: "London, UK", avatar: "JR", text: "I was skeptical about the collagen mask but after the first night I woke up and my skin looked insane. Plump, dewy, glowing.", product: "Bio-Collagen Mask", rating: 5 },
  { name: "Amara K.", location: "Toronto, CA", avatar: "AK", text: "Finally a self-tanner that doesn't smell or streak. The drops are so easy to control. I mix 3 drops every other night.", product: "Self-Tan Drops", rating: 5 },
  { name: "Priya L.", location: "Sydney, AU", avatar: "PL", text: "6 weeks in and my lashes are genuinely longer. My ophthalmologist even commented. Worth every cent at this price.", product: "Eyelash Serum", rating: 5 },
];

export const STATS = [
  { value: "31K+", label: "5-Star Reviews" },
  { value: "4.6", label: "Avg. Rating" },
  { value: "6", label: "Trend-Scored Products" },
  { value: "92%", label: "Would Repurchase" },
];
